Api contract for users/userAvailble/:id route
Real-Dev-Squad/website-api-contracts pull request #20
Opened 2021-01-28 05:44 UTC by saishankarmanugula

![image](https://user-images.githubusercontent.com/11243646/106095526-f4160700-6159-11eb-96ce-392accfc7af8.png)

2021-01-29 07:45 UTC, swarajpure reviewed
Have some doubts, please clarify.

2021-01-29 07:45 UTC, swarajpure commented on users/README.md
> +  _Required:_ `id=[string]`
re: `id`

2021-01-29 07:45 UTC, swarajpure commented on users/README.md
> +Returns the availability of user name.
Please combine and make it `username`

2021-01-29 07:45 UTC, swarajpure commented on users/README.md
> +## **GET /users/userAvailable/:id**
There should be `username` instead of `id`, right?

2021-01-29 07:45 UTC, swarajpure commented on users/README.md
> +    - **Content:** `{ 'userAvailable': <Availability Stauts> }`
Something like `isUsernameAvailable` sounds better to me. What do you say?
Also the value should be <boolean>

2021-02-03 04:36 UTC, swarajpure requested changes
Looks good to me 👍🏻 

Also, if this route is going to require authentication (which I think it would), please add 4xx error response for unauthorized user
Also, kindly add 5xx error for server error response

You can refer contracts for other `users` routes to get idea of the above two error responses.

Thank you 🎉

2021-02-21 13:54 UTC, swarajpure approved these changes
Great! Thank you! 🎉

2021-02-21 19:04 UTC, ankushdharkar approved these changes

2021-02-21 19:04 UTC, ankushdharkar commented
This looks good. Thanks @saishankarmanugula!

2021-02-21 19:05 UTC, merged