updated the API  contract for the route GET tasks/self
Real-Dev-Squad/website-api-contracts pull request #25
Opened 2021-02-04 13:45 UTC by Rucha1499

- Updated the description of the route `tasks/self` in the contract.
- Added the Query `Completed=[boolean]`.

2021-02-04 21:45 UTC, sumitd94 requested changes
One small fix and then looks good.

2021-02-04 21:45 UTC, sumitd94 commented on tasks/README.md
> +  Completed=[boolean]
should be lowercase `completed=true`

2021-02-05 03:43 UTC, Rucha1499 commented on tasks/README.md
> +  Completed=[boolean]
Done with the changes. Thank you! 😄

2021-02-05 10:26 UTC, sumitd94 approved these changes
Thanks for the changes !

2021-02-05 10:27 UTC, merged