Badges api contracts
Real-Dev-Squad/website-api-contracts pull request #29
Opened 2021-02-07 14:54 UTC by whyDontI

Proposing API contracts for /badges API to be used in the members profile page

2021-02-07 15:06 UTC, ankurnarkhede requested changes

2021-02-07 15:06 UTC, ankurnarkhede commented on badges/README.md
> +  - **Code:** 204
There shouldnt be any body with 204.

2021-02-07 15:06 UTC, ankurnarkhede commented on badges/README.md
> +  rds-session: `<JWT>`
Do we want to allow users to create custom new badge? 🤔

2021-04-11 04:59 UTC, sumitd94 approved these changes
Thanks for the Contract :)

2021-04-11 05:04 UTC, merged