Extension req
Real-Dev-Squad/website-api-contracts pull request #96
Opened 2022-11-08 17:13 UTC by shivampandey0

# API Contracts for Extension Requests.

2022-11-08 17:18 UTC, ivinayakg requested changes

2022-11-08 17:18 UTC, ivinayakg commented on extension-requests/README.md
> +|     [POST /extension-requests](#post-tasks)     | Creates new extension request  |
Get /extension-request/self/?taskId-
patch /extension-request

2022-11-16 13:06 UTC, ivinayakg approved these changes
LGTM 👍
Good Work

2022-11-19 18:15 UTC, Maheima approved these changes
LGTM!

2023-01-06 23:37 UTC, ivinayakg approved these changes

2023-01-06 23:38 UTC, merged